---

- name: configure DHCP options set
  ec2_vpc_dhcp_option:
    profile:        '{{ aws_profile }}'
    aws_access_key: '{{ aws_iam_assume_role_access_key    | default(omit) }}'
    aws_secret_key: '{{ aws_iam_assume_role_secret_key    | default(omit) }}'
    security_token: '{{ aws_iam_assume_role_session_token | default(omit) }}'

    region: '{{ aws_region }}'
    vpc_id: '{{ _aws_vpc_id }}'

    tags:
      Name: '{{ aws_vpc_dhcp_options_set.domain_name | default(omit) }}'

    domain_name: '{{ aws_vpc_dhcp_options_set.domain_name | default(omit) }}'

    dns_servers: '{{ aws_vpc_dhcp_options_set.dns_servers | default(omit) }}'

    netbios_name_servers: >-
      {{ aws_vpc_dhcp_options_set.netbios_name_servers | default(omit) }}
    netbios_node_type: >-
      {{ aws_vpc_dhcp_options_set.netbios_node_type | default(omit) }}

    ntp_servers: '{{ aws_vpc_dhcp_options_set.ntp_servers | default(omit) }}'
