---

- name: configure DHCP options set
  ec2_vpc_dhcp_options:
    profile: '{{ aws_profile }}'
    region: '{{ aws_region }}'
    vpc_id: '{{ _aws_vpc_id }}'

    tags:
      Name: '{{ aws_vpc_dhcp_options.domain_name | default(omit) }}'

    domain_name: '{{ aws_vpc_dhcp_options.domain_name | default(omit) }}'

    dns_servers: '{{ aws_vpc_dhcp_options.dns_servers | default(omit) }}'

    netbios_name_servers: >-
      {{ aws_vpc_dhcp_options.netbios_name_servers | default(omit) }}
    netbios_node_type: >-
      {{ aws_vpc_dhcp_options.netbios_node_type | default(omit) }}

    ntp_servers: '{{ aws_vpc_dhcp_options.ntp_servers | default(omit) }}'
