---

- name: configure Internet gateway
  ec2_vpc_igw:
    profile: '{{ aws_profile }}'
    region: '{{ aws_region }}'
    tags:
      Name: '{{ aws_vpc_name }}'
    vpc_id: '{{ _aws_vpc_id }}'
  register: _aws_vpc_igw
