---

- name: configure Internet gateway
  ec2_vpc_igw:
    profile: '{{ aws_profile }}'
    region: '{{ aws_region }}'
    vpc_id: '{{ _aws_vpc_id }}'
  register: _aws_vpc_igw

- name: set Internet gateway name tag
  ec2_tag:
    profile: '{{ aws_profile }}'
    region: '{{ aws_region }}'
    resource: '{{ _aws_vpc_igw.gateway_id }}'
    tags:
      Name: '{{ aws_vpc_name }}'
