---

- name: configure Internet gateway
  ec2_vpc_igw:
    profile:        '{{ aws_profile }}'
    aws_access_key: '{{ aws_iam_assume_role_access_key    | default(omit) }}'
    aws_secret_key: '{{ aws_iam_assume_role_secret_key    | default(omit) }}'
    security_token: '{{ aws_iam_assume_role_session_token | default(omit) }}'

    region: '{{ aws_region }}'
    tags:
      Name: '{{ aws_vpc_name }}'
    vpc_id: '{{ _aws_vpc_id }}'
  register: _aws_vpc_igw
