---

- name: set global facts
  set_fact:
    _aws_vpc_url: >-
      https://console.aws.amazon.com/vpc/home?region={{ aws_region
        }}#vpcs:filter=^{{ aws_vpc_name }}$

- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      started running role <b>aws-vpc</b> on
      <a href="{{ _aws_vpc_url }}">VPC {{ aws_vpc_name }}</a>
  when: notifier_role is defined

- include: vpc_id.yml
- include: nat_id.yml
- include: vgw_ids.yml

- include: route_igw.yml
- include: route_nat.yml
- include: routes_pcxs.yml

- include: routes_private.yml
- include: routes_public.yml

- include: vpc.yml
- include: dhcp_options.yml
- include: igw.yml
- include: cgw.yml
- include: subnets.yml
- include: rtbs.yml
- include: sgs.yml

- include: nat.yml

- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      finished running role <b>aws-vpc</b> on
      <a href="{{ _aws_vpc_url }}">VPC {{ aws_vpc_name }}</a>
  when: notifier_role is defined
