---

- name: set global facts
  set_fact:
    _aws_vpc_url: >-
      https://console.aws.amazon.com/vpc/home?region={{ aws_region
        }}#vpcs:filter=^{{ aws_vpc_name }}$

- name: call optional notifier
  include_role:
    name: '{{ notifier_role }}'
  vars:
    message: >
      started running role <b>aws-vpc</b> on
      <a href="{{ _aws_vpc_url }}">VPC {{ aws_vpc_name }}</a>
  when: notifier_role is defined

- include_tasks: vpc.yml

- include_tasks: dhcp_options.yml
- include_tasks: subnets.yml

- include_tasks: igw.yml

- include_tasks: nat_instance.yml
- include_tasks: nat_gateway.yml
- include_tasks: nat_id.yml

- block:
    - include_tasks: cgw.yml
    - include_tasks: vgw.yml
    - include_tasks: vgw_ids.yml
    - include_tasks: vpn.yml
  when: >
    aws_vpc_cgw_site       is defined and
    aws_vpc_cgw_bgp_asn    is defined and
    aws_vpc_cgw_ip_address is defined

- include_tasks: vgw_ids.yml

- include_tasks: route_igw.yml
- include_tasks: route_nat.yml
- include_tasks: routes_pcxs.yml
- include_tasks: routes_private.yml
- include_tasks: routes_public.yml
- include_tasks: rtbs.yml

- include_tasks: vpces.yml

- include_tasks: sgs.yml

- name: call optional notifier
  include_role:
    name: '{{ notifier_role }}'
  vars:
    message: >
      finished running role <b>aws-vpc</b> on
      <a href="{{ _aws_vpc_url }}">VPC {{ aws_vpc_name }}</a>
  when: notifier_role is defined
