---

- include: roles/common/tasks/slack.yml
  vars:
    message: 'started running role *aws-vpc* on *VPC {{ vpc_name }}*'

- include: vpc_id.yml
- include: vgw_id.yml

- include: route_igw.yml
- include: route_nat.yml
- include: routes_pcxs.yml

- include: routes_private.yml
- include: routes_public.yml

- include: vpc.yml
- include: subnets.yml
- include: rtbs.yml

- include: sgs.yml
  vars:
    sg_collection: '{{ security_groups_common }}'
    sg_collection_description: common

- include: sgs.yml
  vars:
    sg_collection: '{{ security_groups }}'
    sg_collection_description: 'VPC-specific'

- include: sg_ids.yml
- include: subnet_ids.yml

- include: roles/aws-ec2/tasks/instance.yml
  vars:
    instance: nat
  when: instances['nat'] is defined

- block:
  - include: route_nat.yml
  - include: routes_private.yml
  - include: rtbs.yml
  - include: roles/common/tasks/slack.yml
    vars:
      message: 'reconfigured *VPC {{ vpc_name }}* to include a *NAT route*'
  when: instances['nat'] is defined and ec2.changed

- include: roles/common/tasks/slack.yml
  vars:
    message: 'finished running role *aws-vpc* on *VPC {{ vpc_name }}*'
