---

- name: set global facts
  set_fact:
    vpc_url: >-
      https://console.aws.amazon.com/vpc/home?region={{ region
        }}#vpcs:filter=^{{ vpc_name }}$

- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      started running role <b>aws-vpc</b> on
      <a href="{{ vpc_url }}">VPC {{ vpc_name }}</a>
  when: notifier_role is defined

- include: vpc_id.yml
- include: vgw_id.yml

- include: route_igw.yml
- include: route_nat.yml
- include: routes_pcxs.yml

- include: routes_private.yml
- include: routes_public.yml

- include: vpc.yml
- include: subnets.yml
- include: rtbs.yml

- include: sgs.yml
  vars:
    sg_collection: '{{ security_groups_common }}'
    sg_collection_description: common

- include: sgs.yml
  vars:
    sg_collection: '{{ security_groups }}'
    sg_collection_description: 'VPC-specific'

- include: sg_ids.yml
- include: subnet_ids.yml

- include: roles/aws-ec2/tasks/instance.yml
  vars:
    instance: nat
  when: 'instances["nat"] is defined'

- block:
  - include: route_nat.yml
  - include: routes_private.yml
  - include: rtbs.yml
  - name: call optional notifier
    include: 'roles/{{ notifier_role }}/tasks/main.yml'
    vars:
      message: >
        added a NAT route to the private route table in
        <a href="{{ vpc_url }}">VPC {{ vpc_name }}</a>
    when: notifier_role is defined
  when: 'instances["nat"] is defined and ec2.changed'

- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      finished running role <b>aws-vpc</b> on
      <a href="{{ vpc_url }}">VPC {{ vpc_name }}</a>
  when: notifier_role is defined
