---

- name: load NAT instance configuration
  include_vars: '{{ item }}'
  with_fileglob: 'host_vars/{{ inventory_hostname }}/ec2/nat.yml'

- name: look up NAT instance configuration
  set_fact:
    _aws_vpc_nat_instance: >
      {{ aws_ec2_instances
         | selectattr("function", "equalto", "nat")
         | first }}
  when: '"nat" in (aws_ec2_instances | map(attribute="function"))'

- include: roles/aws-ec2/tasks/instance.yml
  vars:
    instance: '{{ _aws_vpc_nat_instance }}'
  when: _aws_vpc_nat_instance is defined

- block:
    - include: nat_id.yml
    - include: route_nat.yml
    - include: routes_private.yml
    - include: rtbs.yml
    - name: call optional notifier
      include: 'roles/{{ notifier_role }}/tasks/main.yml'
      vars:
        message: >
          added a <a href="https://console.aws.amazon.com/ec2/v2/home?region={{
            aws_region
          }}#Instances:tag:Function=nat">NAT</a> route to the
          <a href="https://console.aws.amazon.com/vpc/home?region={{
            aws_region
          }}#routetables:filter={{
            _aws_vpc_private_route_table.route_table.id
          }}">private route table</a> in
          <a href="{{ _aws_vpc_url }}">VPC {{ aws_vpc_name }}</a>
      when: notifier_role is defined
  when: _aws_vpc_nat_instance is defined and _aws_ec2_launch.changed
