---

- name: get NAT instance facts
  ec2_remote_facts:
    filters:
      'tag:Function': nat
      vpc-id: '{{ _aws_vpc_id }}'
    profile: '{{ aws_profile }}'
    region: '{{ aws_region }}'
  register: _aws_vpc_nat_instance

- name: set NAT instance ID fact
  set_fact:
    _aws_vpc_nat_instance_id: '{{ _aws_vpc_nat_instance.instances[0].id }}'
