---

- name: get NAT instance facts
  ec2_remote_facts:
    filters:
      'tag:Function': nat
      vpc-id: '{{ _aws_vpc_id }}'
    profile: '{{ aws_profile }}'
    region: '{{ aws_region }}'
  register: _aws_vpc_nat_instance

- name: set NAT instance ID fact
  set_fact:
    _aws_vpc_nat_instance_id: '{{ _aws_vpc_nat_instance.instances[0].id }}'
  when: _aws_vpc_nat_instance.instances | length == 1

- name: set NAT gateway ID fact
  set_fact:
    _aws_vpc_nat_gateway_id: >-
      {% if _aws_vpc_existing_nat_gateway.result | length == 1 %}{{
        _aws_vpc_existing_nat_gateway.result[0].NatGatewayId
      }}{% else %}{{
        _aws_vpc_created_nat_gateway.NatGatewayId
      }}{% endif %}
  when: aws_vpc_nat_gateway
