---

- block:

    - name: load NAT instance configuration
      include_role:
        name: aws-ec2
        tasks_from: instances_load_vars
      vars:
        _aws_ec2_vars_file: 'host_vars/{{ inventory_hostname }}/ec2/nat.yml'

    - name: look up NAT instance configuration
      set_fact:
        _aws_vpc_nat_instance: >
          {{ _aws_ec2_configured_instances
             | selectattr("function", "equalto", "nat")
             | first }}
      when: >
        _aws_ec2_configured_instances is defined and
        "nat" in (_aws_ec2_configured_instances | map(attribute="function"))

    - include_role:
        name: aws-ec2
        tasks_from: instance
      vars:
        _aws_ec2_i: '{{ _aws_vpc_nat_instance }}'
      when: _aws_vpc_nat_instance is defined

  when: not aws_vpc_nat_gateway
