---

- name: create private routes (with NAT instance)
  set_fact:
    routes_private: '{{ [route_nat] + routes_pcxs }}'
  when: route_nat is defined

- name: create private routes (without NAT instance)
  set_fact:
    routes_private: '{{ routes_pcxs }}'
  when: route_nat is not defined
