---

- name: describe VPC peering connections
  command: >
    aws ec2 describe-vpc-peering-connections
            --profile '{{ profile }}'
  register: pcxs
  changed_when: False

- name: create VPC peering connection routes
  set_fact:
    routes_pcxs: '{{ pcxs.stdout
                     | from_json
                     | pcxs_to_routes(vpc_id) }}'
