---

- name: configure public route table
  ec2_vpc_route_table:
    profile: '{{ profile }}'
    region: '{{ region }}'
    vpc_id: '{{ vpc_id }}'
    routes: '{{ routes_public }}'
    propagating_vgw_ids: [ '{{ vgw_id }}' ]
    subnets: '{{ subnets.public | map(attribute="cidr") | list }}'
    resource_tags: { 'Name': 'public' }
  register: ec2_vpc_route_table

- name: call optional notifier
  include: roles/{{ notifier_role }}/tasks/main.yml
  vars:
     message: 'configured *public route table* in *VPC {{ vpc_name }}*'
  when: notifier_role is defined and
        ec2_vpc_route_table.changed

- name: check for blackhole default route in private route table
  command: aws ec2 describe-route-tables
             --filters Name=tag:Name,Values=private
             --query 'RouteTables[0].Routes[?State == `blackhole`]
                          | [?DestinationCidrBlock == `0.0.0.0/0`]'
             --output text
             --profile '{{ profile }}'
  register: blackhole_default_route
  changed_when: False

- block:

  - name: get private route table ID
    command: aws ec2 describe-route-tables
               --filters Name=tag:Name,Values=private
               --query 'RouteTables[0].RouteTableId'
               --output text
               --profile '{{ profile }}'
    register: private_route_table_id
    changed_when: False

  - name: delete blackhole default route
    command: aws ec2 delete-route
               --route-table-id '{{ private_route_table_id.stdout }}'
               --destination-cidr-block 0.0.0.0/0
               --profile '{{ profile }}'

  when: blackhole_default_route.stdout != ''

- name: configure private route table
  ec2_vpc_route_table:
    profile: '{{ profile }}'
    region: '{{ region }}'
    vpc_id: '{{ vpc_id }}'
    routes: '{{ routes_private }}'
    propagating_vgw_ids: [ '{{ vgw_id }}' ]
    subnets: '{{ subnets.private | map(attribute="cidr") | list }}'
    resource_tags: { 'Name': 'private' }
  register: ec2_vpc_route_table

- name: call optional notifier
  include: roles/{{ notifier_role }}/tasks/main.yml
  vars:
     message: 'configured *private route table* in *VPC {{ vpc_name }}*'
  when: notifier_role is defined and
        ec2_vpc_route_table.changed
