---

- name: configure public route table
  ec2_vpc_route_table:
    profile:        '{{ aws_profile }}'
    aws_access_key: '{{ aws_iam_assume_role_access_key    | default(omit) }}'
    aws_secret_key: '{{ aws_iam_assume_role_secret_key    | default(omit) }}'
    security_token: '{{ aws_iam_assume_role_session_token | default(omit) }}'

    region: '{{ aws_region }}'
    vpc_id: '{{ _aws_vpc_id }}'
    routes: '{{ _aws_vpc_routes_public }}'
    propagating_vgw_ids: '{{ _aws_vpc_vgw_ids | default(omit) }}'
    subnets: '{{ aws_vpc_subnets.public | map(attribute="cidr") | list }}'
    resource_tags: { 'Name': 'public' }
  register: _aws_vpc_public_route_table
  when: aws_vpc_subnets.public is defined

- name: call optional notifier
  include_tasks: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      configured the <a href="https://console.aws.amazon.com/vpc/home?region={{
        aws_region
      }}#routetables:filter={{
        _aws_vpc_public_route_table.route_table.id
      }}">public route table</a> in
      <a href="{{ _aws_vpc_url }}">VPC {{ aws_vpc_name }}</a>
  when: >
    notifier_role is defined and
    _aws_vpc_public_route_table.changed


- name: configure private route table
  ec2_vpc_route_table:
    profile:        '{{ aws_profile }}'
    aws_access_key: '{{ aws_iam_assume_role_access_key    | default(omit) }}'
    aws_secret_key: '{{ aws_iam_assume_role_secret_key    | default(omit) }}'
    security_token: '{{ aws_iam_assume_role_session_token | default(omit) }}'

    region: '{{ aws_region }}'
    vpc_id: '{{ _aws_vpc_id }}'
    routes: '{{ _aws_vpc_routes_private }}'
    propagating_vgw_ids: '{{ _aws_vpc_vgw_ids | default(omit) }}'
    subnets: '{{ aws_vpc_subnets.private | map(attribute="cidr") | list }}'
    resource_tags: { 'Name': 'private' }
  register: _aws_vpc_private_route_table
  when: aws_vpc_subnets.private is defined

- name: call optional notifier
  include_tasks: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      configured the <a href="https://console.aws.amazon.com/vpc/home?region={{
        aws_region
      }}#routetables:filter={{
        _aws_vpc_private_route_table.route_table.id
      }}">private route table</a> in
      <a href="{{ _aws_vpc_url }}">VPC {{ aws_vpc_name }}</a>
  when: >
    notifier_role is defined and
    _aws_vpc_private_route_table.changed
