---

- name: configure public route table
  ec2_vpc_route_table:
    profile: '{{ aws_profile }}'
    region: '{{ aws_region }}'
    vpc_id: '{{ vpc_id }}'
    routes: '{{ routes_public }}'
    propagating_vgw_ids: [ '{{ vgw_id }}' ]
    subnets: '{{ subnets.public | map(attribute="cidr") | list }}'
    resource_tags: { 'Name': 'public' }
  register: public_route_table

- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      configured the <a href="https://console.aws.amazon.com/vpc/home?region={{
        aws_region
      }}#routetables:filter={{
        public_route_table.route_table.id
      }}">public route table</a> in
      <a href="{{ vpc_url }}">VPC {{ aws_vpc_name }}</a>
  when: >
    notifier_role is defined and
    public_route_table.changed

- name: check for blackhole default route in private route table
  command: >
    aws ec2 describe-route-tables
            --filters Name=tag:Name,Values=private
            --query 'RouteTables[0].Routes[?State == `blackhole`]
                         | [?DestinationCidrBlock == `0.0.0.0/0`]'
            --output text
            --profile '{{ aws_profile }}'
  register: blackhole_default_route
  changed_when: False

- block:

  - name: get private route table ID
    command: >
      aws ec2 describe-route-tables
              --filters Name=tag:Name,Values=private
              --query 'RouteTables[0].RouteTableId'
              --output text
              --profile '{{ aws_profile }}'
    register: private_route_table_id
    changed_when: False

  - name: delete blackhole default route
    command: >
      aws ec2 delete-route
              --route-table-id '{{ private_route_table_id.stdout }}'
              --destination-cidr-block 0.0.0.0/0
              --profile '{{ aws_profile }}'

  - name: call optional notifier
    include: 'roles/{{ notifier_role }}/tasks/main.yml'
    vars:
      message: >
        deleted a blackhole default route from the
        <a href="https://console.aws.amazon.com/vpc/home?region={{
          aws_region
        }}#routetables:filter={{
          private_route_table_id.stdout
        }}">private route table</a> in
        <a href="{{ vpc_url }}">VPC {{ aws_vpc_name }}</a>
    when: >
      notifier_role is defined

  when: >
    blackhole_default_route.stdout != '' and
    blackhole_default_route.stdout != 'None'

- name: configure private route table
  ec2_vpc_route_table:
    profile: '{{ aws_profile }}'
    region: '{{ aws_region }}'
    vpc_id: '{{ vpc_id }}'
    routes: '{{ routes_private }}'
    propagating_vgw_ids: [ '{{ vgw_id }}' ]
    subnets: '{{ subnets.private | map(attribute="cidr") | list }}'
    resource_tags: { 'Name': 'private' }
  register: private_route_table

- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      configured the <a href="https://console.aws.amazon.com/vpc/home?region={{
        aws_region
      }}#routetables:filter={{
        private_route_table.route_table.id
      }}">private route table</a> in
      <a href="{{ vpc_url }}">VPC {{ aws_vpc_name }}</a>
  when: >
    notifier_role is defined and
    private_route_table.changed
