---

- name: 'configure security groups ({{ sg_collection_description }})'
  ec2_group:

    name: '{{ item.key }}'
    description: '{{ item.value.description | default(None) }}'
    profile: '{{ profile }}'
    vpc_id: '{{ vpc_id }}'
    region: '{{ region }}'
    state: '{{ item.value.state | default("present") }}'

    rules: '{{ item.value.rules | default(None) }}'
    rules_egress: '{{ item.value.rules_egress | default(None) }}'

  with_dict: '{{ sg_collection | default({}) }}'
  register: ec2_group

- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      updated <b>security groups ({{ sg_collection_description }})</b>
      in <b>VPC {{ vpc_name }}</b>
  when: >
    notifier_role is defined and
    ec2_group.changed
