---

- name: 'configure security groups ({{ sg_collection_description }})'
  ec2_group:

    name: '{{ item.key }}'
    description: '{{ item.value.description | default(None) }}'
    profile: '{{ aws_profile }}'
    vpc_id: '{{ vpc_id }}'
    region: '{{ region }}'
    state: '{{ item.value.state | default("present") }}'

    rules: '{{ item.value.rules | default(None) }}'
    rules_egress: '{{ item.value.rules_egress | default(None) }}'

  with_dict: '{{ sg_collection | default({}) }}'
  register: ec2_group

- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      updated the <a href="https://console.aws.amazon.com/ec2/v2/home?region={{
        region
      }}#SecurityGroups">{{ sg_collection_description }} security groups</a>
      in <a href="{{ vpc_url }}">VPC {{ vpc_name }}</a>
  when: >
    notifier_role is defined and
    ec2_group.changed
