---

- name: configure subnets
  ec2_vpc_subnet:
    az: '{{ item.az }}'
    cidr: '{{ item.cidr }}'
    profile: '{{ aws_profile }}'
    region: '{{ aws_region }}'
    resource_tags: '{{ item.resource_tags }}'
    state: present
    vpc_id: '{{ _aws_vpc_id }}'
  with_items: >
    {{ aws_vpc_subnets.public  | default([]) }} +
    {{ aws_vpc_subnets.private | default([]) }}
  register: _aws_vpc_subnet

- name: call optional notifier
  include_tasks: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      configured <a href="https://console.aws.amazon.com/vpc/home?region={{
        aws_region
      }}#subnets:">subnets</a> in
      <a href="{{ _aws_vpc_url }}">VPC {{ aws_vpc_name }}</a>
  when: >
    notifier_role is defined and
    _aws_vpc_subnet.changed
