---

- name: describe subnets
  command: aws ec2 describe-subnets
  environment:
    AWS_DEFAULT_PROFILE: '{{ vpc_name }}'
  register: subnets_data
  changed_when: False

- name: convert subnet data to JSON
  set_fact:
    subnets_json: '{{ subnets_data.stdout | from_json }}'

- name: extract subnet IDs and store them by name
  set_fact:
    subnet_ids_by_name: '{{ subnets_json.Subnets | get_subnet_ids_by_name(vpc_id) }}'
