---

- name: get virtual gateways
  command: >
    aws ec2 describe-vpn-gateways
            --query
              'VpnGateways[?VpcAttachments[?VpcId == `{{ _aws_vpc_id }}` &&
                                            State == `attached`]]
               .VpnGatewayId'
            --profile '{{ aws_profile }}'
  register: _aws_vpc_vgw_ids
  changed_when: False

- name: set virtual gateways fact
  set_fact:
    _aws_vpc_vgw_ids: '{{ _aws_vpc_vgw_ids.stdout | from_json }}'
