---

- name: select virtual gateway
  command: >
    aws ec2 describe-vpn-gateways
            --query 'VpnGateways[?VpcAttachments[?VpcId == `{{ vpc_id }}` &&
                                                  State == `attached`]]
                     .VpnGatewayId'
            --output text
            --profile '{{ profile }}'
  register: vgw_id
  changed_when: False

- debug: var=vgw_id

- name: set virtual gateway fact
  set_fact:
    vgw_id: '{{ vgw_id.stdout }}'

- debug: var=vgw_id
