---

- name: get virtual gateways
  ec2_vpc_vgw_facts:
    filters:
      attachment.state: ['attaching', 'attached']
      attachment.vpc-id: '{{ _aws_vpc_id }}'
      state: ['pending', 'available']
    profile: '{{ aws_profile }}'
    region: '{{ aws_region }}'
  register: _aws_vpc_vgw_ids

- name: set virtual gateways fact
  set_fact:
    _aws_vpc_vgw_ids: >-
      {{
        _aws_vpc_vgw_ids.virtual_gateways
        | json_query("
            [?
              vpc_attachments
                [?
                     (state == `attaching` || state == `attached`)
                  && vpc_id == `" + _aws_vpc_id + "`
                ]
            ]
            .
            vpn_gateway_id
          ")
      }}
