---

- name: configure VPC
  ec2_vpc:

    profile: '{{ aws_profile }}'
    region: '{{ aws_region }}'
    resource_tags: { 'Name': '{{ aws_vpc_name }}' }
    cidr_block: '{{ aws_vpc_cidr_block }}'
    state: present

    internet_gateway: yes

    wait: yes

  register: _aws_vpc_configuration

- name: set VPC ID fact
  set_fact:
    _aws_vpc_id: '{{ _aws_vpc_configuration.vpc_id }}'
  when: _aws_vpc_configuration.changed

- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
     message: >
       created <a href="{{ _aws_vpc_url }}">VPC {{ aws_vpc_name }}</a>
  when: >
    notifier_role is defined and
    _aws_vpc_configuration.changed
