---

- name: configure VPC
  ec2_vpc_net:
    cidr_block: '{{ aws_vpc_cidr_block }}'
    name: '{{ aws_vpc_name }}'
    region: '{{ aws_region }}'
    profile: '{{ aws_profile }}'
    state: present
  register: _aws_vpc_configuration

- name: set VPC ID fact
  set_fact:
    _aws_vpc_id: '{{ _aws_vpc_configuration.vpc.id }}'

- name: call optional notifier
  include_role:
    name: '{{ notifier_role }}'
  vars:
     message: >
       created <a href="{{ _aws_vpc_url }}">VPC {{ aws_vpc_name }}</a>
  when: >
    notifier_role is defined and
    _aws_vpc_configuration.changed
