---

- name: configure VPC
  ec2_vpc:

    profile: '{{ profile }}'
    region: '{{ region }}'
    resource_tags: { 'Name': '{{ vpc_name }}' }
    cidr_block: '{{ cidr_block }}'
    state: present

    internet_gateway: yes

  register: ec2_vpc

- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
     message: 'configured <a href="{{ vpc_url }}">VPC {{ vpc_name }}</a>'
  when: >
    notifier_role is defined and
    ec2_vpc.changed
