---

- name: configure VPC
  environment:
    AWS_PROFILE: '{{ vpc_name }}'
  ec2_vpc:

    region: '{{ region }}'
    resource_tags: { 'Name': '{{ vpc_name }}' }
    cidr_block: '{{ cidr_block }}'
    state: present

    internet_gateway: yes

  register: ec2_vpc

- include: roles/common/tasks/slack.yml
  vars:
     message: 'configured *VPC {{ vpc_name }}*'
  when: ec2_vpc.changed
