---

- name: describe VPCs
  command: >
    aws ec2 describe-vpcs
            --filters Name=tag:Name,Values={{ aws_vpc_name }}
            --query 'Vpcs[].VpcId'
            --output text
            --profile '{{ aws_profile }}'
  register: _aws_vpc_id
  changed_when: False

- name: set VPC ID fact
  set_fact:
    _aws_vpc_id: '{{ _aws_vpc_id.stdout }}'
