---

- name: describe VPCs
  command: >
    aws ec2 describe-vpcs
            --filters Name=tag:Name,Values={{ vpc_name }}
            --query 'Vpcs[].VpcId'
            --output text
            --profile '{{ aws_profile }}'
  register: vpc_id
  changed_when: False

- name: set VPC ID fact
  set_fact:
    vpc_id: '{{ vpc_id.stdout }}'
