---

- name: get VPC facts
  ec2_vpc_net_facts:
    filters:
      'tag:Name': '{{ aws_vpc_name }}'
    profile: '{{ aws_profile }}'
    region: '{{ aws_region }}'
  register: _aws_vpc

- name: set VPC ID fact
  set_fact:
    _aws_vpc_id: '{{ _aws_vpc.vpcs[0].id }}'
