---

- name: configure S3 VPC endpoint
  ec2_vpc_endpoint:
    profile: '{{ aws_profile }}'
    region: '{{ aws_region }}'
    route_table_ids:
      - '{{ _aws_vpc_public_route_table.route_table.id }}'
      - '{{ _aws_vpc_private_route_table.route_table.id }}'
    service: 'com.amazonaws.{{ aws_region }}.s3'
    vpc_id: '{{ _aws_vpc_id }}'
  register: _aws_vpc_endpoint
  when: >
    _aws_vpc_public_route_table.route_table  is defined and
    _aws_vpc_private_route_table.route_table is defined

- name: call optional notifier
  include_tasks: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      added an <a href="https://console.aws.amazon.com/vpc/home?region={{
        aws_region
      }}#Endpoints:vpcEndpointId={{
        _aws_vpc_endpoint.result.vpc_endpoint_id
      }}">S3 VPC endpoint</a> in
      <a href="{{ _aws_vpc_url }}">VPC {{ aws_vpc_name }}</a>
  when: >
    notifier_role is defined and
    _aws_vpc_endpoint.changed
