---

- name: create VPN connection
  ec2_vpc_vpn:
    customer_gateway_id: '{{ _aws_vpc_cgw_id }}'
    profile: '{{ aws_profile }}'
    region: '{{ aws_region }}'
    tags:
      Name: '{{ aws_vpc_name }} + {{ aws_vpc_cgw_site }}'
    vpn_gateway_id: '{{ _aws_vpc_vgw_id }}'
  register: _aws_vpc_vpn
